### ISSUE TITLE
SSL "Internal error" when spinning up the client 

### ISSUE THREAD

**Issue by emphasize** [JarbasHiveMind/hivemind_websocket_client#3]
There might be something missing in `sslopt` ([#](https://github.com/JarbasHiveMind/hivemind_websocket_client/blob/0cc58be4e7b84e006c7ad26765c769c1e7896c95/hivemind_bus_client/client.py#L130))

packages: newest dev
client present in clients.db (mycroft node): yes             (double checked the values)

```
2022-01-20 15:39:08,258 [DEBUG]         [doorpi.event.handler] [3P7Q73] Executing 2 action(s) for OnStartup
2022-01-20 15:39:08,259 [DEBUG]         [doorpi.event.handler] [3P7Q73] Executing Connecting mycroft
2022-01-20 15:39:08,259 [DEBUG]         [doorpi.actions.mycroft.connect] Creating new mycroft connect instance
2022-01-20 15:39:14,183 [INFO]          [HiveMind-presence] Fetching Node data: http://192.168.188.29:8088/device.xml
2022-01-20 15:39:14,197 [INFO]          [HiveMind-presence] UpNp Node Found: 192.168.188.29:5678
# logs added
2022-01-20 15:39:14,199 [INFO]          [HiveMind-websocket-client] crypto_key: x #  (16-char)
2022-01-20 15:39:14,199 [INFO]          [HiveMind-websocket-client] SSL: True
2022-01-20 15:39:14,200 [INFO]          [HiveMind-websocket-client] host: 192.168.188.29
2022-01-20 15:39:14,200 [INFO]          [HiveMind-websocket-client] port: 5678
2022-01-20 15:39:14,201 [INFO]          [HiveMind-websocket-client] key: x
2022-01-20 15:39:14,201 [INFO]          [HiveMind-websocket-client] useragent: HiveMind-websocket-client
#
2022-01-20 15:39:14,212 [ERROR]         [HiveMind-websocket-client] === SSLError(1, '[SSL] internal error (_ssl.c:1131)') ===
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/websocket_client-1.2.3-py3.8.egg/websocket/_app.py", line 312, in run_forever
    self.sock.connect(
  File "/usr/local/lib/python3.8/dist-packages/websocket_client-1.2.3-py3.8.egg/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/usr/local/lib/python3.8/dist-packages/websocket_client-1.2.3-py3.8.egg/websocket/_http.py", line 136, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/usr/local/lib/python3.8/dist-packages/websocket_client-1.2.3-py3.8.egg/websocket/_http.py", line 274, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/usr/local/lib/python3.8/dist-packages/websocket_client-1.2.3-py3.8.egg/websocket/_http.py", line 250, in _wrap_sni_socket
    return context.wrap_socket(
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL] internal error (_ssl.c:1131)
```

**Comment by emphasize** [comment]
tossing "ssl_version": ssl.PROTOCOL_TLSv1 got it running
